name       : openrct2
version    : 0.4.1
release    : 31
source     :
    - git|https://github.com/OpenRCT2/OpenRCT2.git : v0.4.1
    - https://github.com/OpenRCT2/title-sequences/releases/download/v0.4.0/title-sequences.zip : 6e7c7b554717072bfc7acb96fd0101dc8e7f0ea0ea316367a05c2e92950c9029
    - https://github.com/OpenRCT2/objects/releases/download/v1.3.2/objects.zip : b87ab1e343930e6263cc7ae803ff35059d53be1d7b5a37a34577c5107c8bbdea
license    : GPL-3.0-or-later
component  : games.strategy
homepage   : https://openrct2.io/
summary    : A construction and management simulation video game that simulates amusement park management
description: |
    OpenRCT2 is an open-source re-implementation of RollerCoaster Tycoon 2 (RCT2). The gameplay revolves around building and maintaining an amusement park containing attractions, shops and facilities. The player must try to make a profit and maintain a good park reputation whilst keeping the guests happy. OpenRCT2 allows for both scenario and sandbox play. Scenarios require the player to complete a certain objective in a set time limit whilst sandbox allows the player to build a more flexible park with optionally no restrictions or finance. Original RollerCoaster Tycoon 2 game files are required in order to play OpenRCT2.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libzip)
    - pkgconfig(nlohmann_json)
    - pkgconfig(sdl2)
    - pkgconfig(speexdsp)
    - pkgconfig(vorbisfile)
rundeps    :
    - innoextract
environment: |
    # GCC throws a false warning for std::optional, should be fixed in GCC 12.3
    export GCC_IGNORE_WERROR=1
setup      : |
    %cmake_ninja \
        -DDOWNLOAD_OBJECTS=OFF \
        -DDOWNLOAD_TITLE_SEQUENCES=OFF \
        -DSTATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke useless -devel
    rm -v $installdir/%libdir%/*.a
    rmdir $installdir/%libdir%

    unzip $sources/title-sequences.zip -d $installdir/usr/share/openrct2/sequence/
    unzip $sources/objects.zip -d $installdir/usr/share/openrct2/object/
