name       : openrct2
version    : 0.1.1
release    : 3
source     :
    - https://github.com/OpenRCT2/OpenRCT2/archive/v0.1.1.tar.gz : 5d7a6c7f3c770e7de506958f86789c438c543c27d312fd096322cde4e89f50ad
license    : GPL-3.0
component  : games.strategy
summary    : An open source re-implementation of Roller Coaster Tycoon 2
description: |
    An open source re-implementation of Roller Coaster Tycoon 2
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jansson)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(speex)
    - pkgconfig(x11)
    - bzip2-devel
networking : yes
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC=0 ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    # Nuke useless -devel
    rm -v $installdir/%libdir%/*.a
    rmdir $installdir/%libdir%
