name       : openrct2
version    : 0.4.3
release    : 33
source     :
    - git|https://github.com/OpenRCT2/OpenRCT2.git : v0.4.3
    - https://github.com/OpenRCT2/title-sequences/releases/download/v0.4.0/title-sequences.zip : 6e7c7b554717072bfc7acb96fd0101dc8e7f0ea0ea316367a05c2e92950c9029
    - https://github.com/OpenRCT2/objects/releases/download/v1.3.7/objects.zip : d6be9743c68f233674f5549204637b1f0304d7567a816d18e3f1576500a51d38
    - https://github.com/OpenRCT2/OpenSoundEffects/releases/download/v1.0.1/opensound.zip : 47dda0925894a48678e1589410d27bbf932295e5e1be3e9ed6ba1bd62a5e3966
    - https://github.com/OpenRCT2/OpenMusic/releases/download/v1.0.1/openmusic.zip : 9f3a171233f7165bc8c66b5c7dfd33f5956dde72ba3a7a9f3ee243c87235c06b
license    :
    - CC-BY-4.0
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
    - MIT
component  : games.strategy
homepage   : https://openrct2.io/
summary    : A construction and management simulation video game that simulates amusement park management
description: |
    OpenRCT2 is an open-source re-implementation of RollerCoaster Tycoon 2 (RCT2). The gameplay revolves around building and maintaining an amusement park containing attractions, shops and facilities. The player must try to make a profit and maintain a good park reputation whilst keeping the guests happy. OpenRCT2 allows for both scenario and sandbox play. Scenarios require the player to complete a certain objective in a set time limit whilst sandbox allows the player to build a more flexible park with optionally no restrictions or finance. Original RollerCoaster Tycoon 2 game files are required in order to play OpenRCT2.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libzip)
    - pkgconfig(nlohmann_json)
    - pkgconfig(sdl2)
    - pkgconfig(speexdsp)
    - pkgconfig(vorbisfile)
rundeps    :
    - innoextract
patterns   :
    - /usr/share/doc/openrct2/changelog.txt
environment: |
    # GCC throws a false warning for std::optional, should be fixed in GCC 12.3
    export GCC_IGNORE_WERROR=1
setup      : |
    %cmake_ninja \
        -DDOWNLOAD_OBJECTS=OFF \
        -DDOWNLOAD_OPENMSX=OFF \
        -DDOWNLOAD_OPENSFX=OFF \
        -DDOWNLOAD_TITLE_SEQUENCES=OFF \
        -DSTATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke useless -devel
    rm -v $installdir/%libdir%/*.a
    rmdir $installdir/%libdir%

    # Nuke unneeded docs
    rm -v $installdir/usr/share/doc/openrct2/contributors.md
    rm -v $installdir/usr/share/doc/openrct2/licence.txt
    rm -v $installdir/usr/share/doc/openrct2/openrct2.d.ts

    unzip $sources/title-sequences.zip -d $installdir/usr/share/openrct2/sequence/
    unzip $sources/objects.zip -d $installdir/usr/share/openrct2/object/
    unzip $sources/opensound.zip -d $installdir/usr/share/openrct2/
    unzip $sources/openmusic.zip -d $installdir/usr/share/openrct2/
